# Generated by Django 4.0.3 on 2022-04-10 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_historicaluser_image_remove_user_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
