# Generated by Django 4.0.3 on 2022-04-01 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=100)),
                ('state', models.SmallIntegerField(default=1)),
                ('icon_name', models.CharField(blank=True, default='ban', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.CharField(max_length=100)),
                ('instruction', models.CharField(max_length=100)),
                ('phrase_translate', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.IntegerField(default=20)),
                ('state', models.SmallIntegerField(default=1)),
                ('icon_name', models.CharField(blank=True, default='ban', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message_motivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=100)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='assets/exercises/', verbose_name='Imagen de la opción')),
                ('state', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('android_version', models.CharField(max_length=5)),
                ('birth', models.DateField()),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('create_date', models.DateField(auto_now_add=True)),
                ('dni', models.CharField(blank=True, max_length=8, null=True, unique=True)),
                ('father_lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=1)),
                ('mother_lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('password', models.CharField(max_length=255)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='assets/profile/', verbose_name='Imagen de perfil')),
                ('state', models.SmallIntegerField(default=1)),
                ('current_score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Type_exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_exercise', models.CharField(max_length=100)),
                ('state', models.SmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='List_options_exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiBackend.exercise')),
                ('option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiBackend.option')),
            ],
        ),
        migrations.CreateModel(
            name='List_exercises_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiBackend.category')),
                ('exercise', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiBackend.exercise')),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='message_motivation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiBackend.message_motivation'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='type_exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiBackend.type_exercise'),
        ),
    ]
