# Generated by Django 4.0.3 on 2022-04-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('category', models.CharField(max_length=100)),
                ('icon_name', models.CharField(blank=True, default='ban', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('exercise', models.CharField(max_length=100)),
                ('instruction', models.CharField(max_length=100)),
                ('phrase_translate', models.CharField(blank=True, max_length=100, null=True)),
                ('score', models.IntegerField(default=20)),
                ('icon_name', models.CharField(blank=True, default='ban', max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 'Exercises',
            },
        ),
        migrations.CreateModel(
            name='Learning',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('image', models.ImageField(blank=True, default='assets/dfImage.jpg', null=True, upload_to='assets/learning/', verbose_name='Image del theme')),
                ('theme', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Learning',
                'verbose_name_plural': 'Learnings',
            },
        ),
        migrations.CreateModel(
            name='List_exercises_category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'List_exercises_category',
                'verbose_name_plural': 'List_exercises_categories',
            },
        ),
        migrations.CreateModel(
            name='List_options_exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'List_options_exercise',
                'verbose_name_plural': 'List_options_exercises',
            },
        ),
        migrations.CreateModel(
            name='List_options_learning',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'List_options_learning',
                'verbose_name_plural': 'List_options_learnings',
            },
        ),
        migrations.CreateModel(
            name='Message_motivation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('message', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Message_motivation',
                'verbose_name_plural': 'Message_motivations',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('option', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, default='assets/dfImage.jpg', null=True, upload_to='assets/exercises/', verbose_name='Imagen de la opción')),
                ('is_correct', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Option',
                'verbose_name_plural': 'Options',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('gender', models.CharField(choices=[('F', 'Female'), ('M', 'Male')], default='F', max_length=1)),
                ('avatar', models.CharField(default=' ', max_length=15)),
                ('current_score', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='Type_exercise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True, verbose_name='Estado')),
                ('type_exercise', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Type_exercise',
                'verbose_name_plural': 'Type_exercises',
            },
        ),
    ]
