# Generated by Django 4.0.3 on 2022-04-16 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apiBackend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='list_options_learning',
            name='learning',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiBackend.learning'),
        ),
        migrations.AddField(
            model_name='list_options_learning',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiBackend.option'),
        ),
        migrations.AddField(
            model_name='list_options_exercise',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiBackend.exercise'),
        ),
        migrations.AddField(
            model_name='list_options_exercise',
            name='option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiBackend.option'),
        ),
        migrations.AddField(
            model_name='list_exercises_category',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiBackend.category'),
        ),
        migrations.AddField(
            model_name='list_exercises_category',
            name='exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiBackend.exercise'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='message_motivation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiBackend.message_motivation'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='type_exercise',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiBackend.type_exercise'),
        ),
    ]
