# Generated by Django 4.0.3 on 2022-04-01 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBackend', '0002_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='image',
            field=models.ImageField(blank=True, default='assets/dfImage.jpg', null=True, upload_to='assets/exercises/', verbose_name='Imagen de la opción'),
        ),
    ]
