# Generated by Django 4.0.3 on 2022-04-23 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBackend', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='image',
            field=models.ImageField(blank=True, default='assets/dfImage.jpg', null=True, upload_to='images/learning/', verbose_name='Image del theme'),
        ),
        migrations.AlterField(
            model_name='option',
            name='image',
            field=models.ImageField(blank=True, default='assets/dfImage.jpg', null=True, upload_to='images/exercises/', verbose_name='Imagen de la opción'),
        ),
    ]
