# Generated by Django 4.0.3 on 2022-04-10 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBackend', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='exercise',
            options={'verbose_name': 'Exercise', 'verbose_name_plural': 'Exercises'},
        ),
        migrations.AlterModelOptions(
            name='historicalcategory',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Category'},
        ),
        migrations.AlterModelOptions(
            name='historicalexercise',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Exercise'},
        ),
        migrations.AlterModelOptions(
            name='historicallearning',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Learning'},
        ),
        migrations.AlterModelOptions(
            name='historicallist_exercises_category',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical List_exercises_category'},
        ),
        migrations.AlterModelOptions(
            name='historicallist_options_exercise',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical List_options_exercise'},
        ),
        migrations.AlterModelOptions(
            name='historicallist_options_learning',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical List_options_learning'},
        ),
        migrations.AlterModelOptions(
            name='historicalmessage_motivation',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Message_motivation'},
        ),
        migrations.AlterModelOptions(
            name='historicaloption',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Option'},
        ),
        migrations.AlterModelOptions(
            name='historicalstudent',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Student'},
        ),
        migrations.AlterModelOptions(
            name='historicaltype_exercise',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Type_exercise'},
        ),
        migrations.AlterModelOptions(
            name='learning',
            options={'verbose_name': 'Learning', 'verbose_name_plural': 'Learnings'},
        ),
        migrations.AlterModelOptions(
            name='list_exercises_category',
            options={'verbose_name': 'List_exercises_category', 'verbose_name_plural': 'List_exercises_categories'},
        ),
        migrations.AlterModelOptions(
            name='list_options_exercise',
            options={'verbose_name': 'List_options_exercise', 'verbose_name_plural': 'List_options_exercises'},
        ),
        migrations.AlterModelOptions(
            name='list_options_learning',
            options={'verbose_name': 'List_options_learning', 'verbose_name_plural': 'List_options_learnings'},
        ),
        migrations.AlterModelOptions(
            name='message_motivation',
            options={'verbose_name': 'Message_motivation', 'verbose_name_plural': 'Message_motivations'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'verbose_name': 'Option', 'verbose_name_plural': 'Options'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='type_exercise',
            options={'verbose_name': 'Type_exercise', 'verbose_name_plural': 'Type_exercises'},
        ),
        migrations.AlterField(
            model_name='category',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalexercise',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicalmessage_motivation',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='historicaltype_exercise',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='message_motivation',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='type_exercise',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
