# Generated by Django 4.0.3 on 2022-04-10 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBackend', '0003_alter_category_options_alter_exercise_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmessage_motivation',
            name='message',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message_motivation',
            name='message',
            field=models.CharField(max_length=100),
        ),
    ]
