# Generated by Django 4.0.3 on 2022-04-23 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiBackend', '0003_alter_learning_image_alter_option_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='list_exercises_category',
            name='is_solved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='list_exercises_category',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='apiBackend.student'),
        ),
    ]
