# Generated by Django 4.0.3 on 2022-04-10 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBackend', '0004_alter_historicalmessage_motivation_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaloption',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='option',
            name='state',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
