# Generated by Django 4.0.3 on 2022-04-10 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBackend', '0005_alter_historicaloption_state_alter_option_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learning',
            name='image',
            field=models.ImageField(blank=True, default='dfImage.jpg', null=True, upload_to='assets/learning/', verbose_name='Image del theme'),
        ),
        migrations.AlterField(
            model_name='option',
            name='image',
            field=models.ImageField(blank=True, default='dfImage.jpg', null=True, upload_to='assets/exercises/', verbose_name='Imagen de la opción'),
        ),
    ]
