# Generated by Django 4.0.3 on 2022-04-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBackend', '0006_alter_learning_image_alter_option_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallearning',
            name='image',
            field=models.TextField(blank=True, default='assets/dfImage.jpg', max_length=100, null=True, verbose_name='Image del theme'),
        ),
        migrations.AlterField(
            model_name='historicaloption',
            name='image',
            field=models.TextField(blank=True, default='assets/dfImage.jpg', max_length=100, null=True, verbose_name='Imagen de la opción'),
        ),
        migrations.AlterField(
            model_name='learning',
            name='image',
            field=models.ImageField(blank=True, default='assets/dfImage.jpg', null=True, upload_to='assets/learning/', verbose_name='Image del theme'),
        ),
        migrations.AlterField(
            model_name='option',
            name='image',
            field=models.ImageField(blank=True, default='assets/dfImage.jpg', null=True, upload_to='assets/exercises/', verbose_name='Imagen de la opción'),
        ),
    ]
