# Generated by Django 4.0.3 on 2022-04-13 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiBackend', '0008_remove_historicalexercise_history_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='avatar',
            field=models.CharField(default=' ', max_length=15),
        ),
    ]
