# Generated by Django 4.0.3 on 2022-04-13 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apiBackend', '0009_student_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='dni',
        ),
    ]
